/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106965-g6076dbcb55-20220523"
#endif /* AVUTIL_FFVERSION_H */
